# --------------------
# Define default values
# --------------------

# ==================== Alas ====================

# ==================== Farm ====================

# ==================== Event ====================

EventA:
  EventDaily:
    StageFilter: |-
      A1 > A2 > A3
EventB:
  EventDaily:
    StageFilter: |-
      B1 > B2 > B3
EventC:
  EventDaily:
    StageFilter: |-
      C1 > C2 > C3
EventD:
  EventDaily:
    StageFilter: |-
      D1 > D2 > D3
HospitalEvent:
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: HospitalEvent
    SuccessInterval: 0
    FailureInterval: 120
    ServerUpdate: "00:00"
  HospitalEvent:
    Mode: hard
    Stage: T1
  StopCondition:
    RunCount: 0
    MapAchievement: non_stop
    StageIncrease: false
    GetNewShip: false
    ReachLevel: 0
  Emotion:
    Mode: calculate
    Fleet1Value: 119
    Fleet1Record: 2020-01-01 00:00:00
    Fleet1Control: prevent_yellow_face
    Fleet1Recover: not_in_dormitory
    Fleet1Oath: false
    Fleet1Onsen: false
    Fleet2Value: 119
    Fleet2Record: 2020-01-01 00:00:00
    Fleet2Control: prevent_yellow_face
    Fleet2Recover: not_in_dormitory
    Fleet2Oath: false
    Fleet2Onsen: false

# ==================== Reward ====================

# ==================== DailyReward ====================

# ==================== DailyMission ====================

# ==================== Opsi ====================
